name: catchat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #service
  dio: ^5.4.1
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  flutter_dotenv: ^5.1.0
  flutter_staggered_animations: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.1.0
  build_runner: ^2.4.9
  foundation: ^0.0.5
  json_serializable: ^6.8.0
  flutter_riverpod: ^2.5.1

  #UIs
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  mockito: ^5.4.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/background/
    - assets/images/cats/
    - .env